steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$first-equinox-377202/frontend', './application/frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$first-equinox-377202/frontend']
images:
  - 'gcr.io/$first-equinox-377202/frontend'
